# Generated by Django 5.0.3 on 2024-09-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='abstract',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='AI摘要'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='text',
            field=models.TextField(max_length=8000, verbose_name='正文'),
        ),
    ]
