# Generated by Django 5.0.3 on 2024-09-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_notification_abstract_alter_notification_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='keywords',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='AI关键词'),
        ),
    ]
