# Generated by Django 5.0.3 on 2024-09-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_notification_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='abstract',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='AI摘要'),
        ),
    ]
