# Generated by Django 5.0.3 on 2024-03-17 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='帖子分类')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='院系名称')),
            ],
        ),
        migrations.CreateModel(
            name='PermissionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='权限组名称')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='状态名称')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='通知类型')),
            ],
        ),
        migrations.CreateModel(
            name='Po',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('launcher_uid', models.IntegerField(verbose_name='发布者ID')),
                ('launch_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('text', models.TextField(max_length=6000, verbose_name='正文')),
                ('additional_information', models.TextField(blank=True, default=None, max_length=1000, null=True, verbose_name='附加信息')),
                ('additional_graphics', models.FileField(blank=True, default=None, max_length=30, null=True, upload_to='images/', verbose_name='附加图片')),
                ('view_times', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('likes', models.IntegerField(default=0, verbose_name='赞')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.category', verbose_name='所属分类')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('launcher', models.CharField(max_length=30, verbose_name='发布者')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('text', models.TextField(max_length=6000, verbose_name='正文')),
                ('additional_graphics', models.FileField(blank=True, default=None, max_length=30, null=True, upload_to='images/', verbose_name='附加图片')),
                ('view_times', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.type', verbose_name='通知类型')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('uid', models.IntegerField(verbose_name='UID')),
                ('nickname', models.CharField(max_length=30, verbose_name='昵称')),
                ('qq', models.IntegerField(blank=True, null=True, verbose_name='QQ')),
                ('wechat', models.CharField(blank=True, max_length=30, null=True, verbose_name='微信号')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='姓名')),
                ('stu_id', models.CharField(blank=True, max_length=15, null=True, verbose_name='学工号')),
                ('avatar', models.FileField(blank=True, max_length=30, null=True, upload_to='avatars/', verbose_name='头像')),
                ('regis_time', models.DateTimeField(auto_now_add=True, verbose_name='注册日期')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.department', verbose_name='院系')),
                ('permission_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.permissiongroup', verbose_name='权限组')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.state', verbose_name='账户状态')),
            ],
        ),
    ]
