# Generated by Django 5.0.3 on 2024-03-18 06:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='launch_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='发布时间'),
            preserve_default=False,
        ),
    ]
