# Generated by Django 5.0.3 on 2024-03-18 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_notification_launch_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Po',
            new_name='Post',
        ),
    ]
